# .github/workflows/release.yml
name: release

on:
  workflow_call:
    inputs:
      tag:
        description: 'New tag name'
        required: true
        type: string

# ...

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          message: "Latest release"

